### ISSUE TITLE
Consider publishing this to the WordPress plugin repository

### ISSUE THREAD

**Issue by ghost** [manzhakdotcom/Menu-Extension-for-bbPress#2]
Consider publishing this to the WordPress plugin repository.  

On the bbPress support forums we get numerous topics about users wanting to customize their site to include profile links in their sites menus. In the past us volunteers on the support forum suggested the user to use code to add a menu item if the user is logged in, but you plugin and approach is perfect by the ease of use. 

I would love to suggest this plugin when its published to the WordPress plugin repository. 

Robkk

**Comment by manzhakdotru** [comment]
Thank you. I will do it soon.))

**Comment by manzhakdotcom** [comment]
All done. 
https://wordpress.org/plugins/menu-extension-for-bbpress/
